name: CI + CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node JS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint & Prettier
      run: |
        npm run lint
        
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node JS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run Jest 
      run: |
        npm test
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node JS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build 
      run: npm run build 
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: build-artifact
        path: build

  deploy-surge:
    name: Deploy preview to Surge
    runs-on: ubuntu-latest
    if: github.repository_owner == 'latticesurgery-com' && github.event_name == 'pull_request'
    needs: [build]
    env:
      SURGE_DOMAIN: ${{ format('https://{0}-{1}-pr{2}-preview.surge.sh', github.repository_owner, 
        github.event.repository.name, github.event.pull_request.number) }}
    
    steps:
    - name: Setup Node JS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Download Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: build-artifact
    
    - name: Install Surge
      run: npm install --global surge
      
    - name: Deploy to Surge
      run: surge ./ ${{ env.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
      
    - name: Check if deploy comment exists
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Preview is deployed to 

    - name: Share/Update deployment link
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Preview is deployed to ${{ env.SURGE_DOMAIN }} :sunglasses: 
        edit-mode: replace
